### PR TITLE
Handle pathlib.Path for paths

### LINKED ISSUE #82: Functions taking paths should handle `pathlib.Path` objects

### PR DESCRIPTION
**Pull request by mgeplf**
* fixes #82

### CODE REVIEW

**Comment by mgeplf** [comment]
The docstrings will be updated once we're happy, and the other PR's have been merged.

**Review by wizmer — COMMENTED** [review]
I see that the CI failure will be fixed in #114 
Other than that LGTM

**Review by matz-e — APPROVED** [review]
LGTM

**Comment by mgeplf** [comment]
Thanks.

**Pull request merged**
