### PR TITLE
Absolute/RelativeShotNoise input: replace amp_cv with relative_skew

### PR DESCRIPTION
**Pull request by WeinaJi**
Sonata specs: https://github.com/BlueBrain/sonata-extension/pull/59

### CODE REVIEW

**Review by darshanmandge — APPROVED** [review]
Thanks. This change looks good to the Cells team.

**Review by jorblancoa — APPROVED** [review]

**Comment by WeinaJi** [comment]
> Thanks. This change looks good to the Cells team.

@darshanmandge Thank you for the review. I have also updated the simulation parser in the previous two PRs that I forgot to inform you.
https://github.com/BlueBrain/libsonata/pull/359
https://github.com/BlueBrain/libsonata/pull/358
Once a new tag is created and deployed on bb5, you will probably see the difference on your side.

**Comment by darshanmandge** [comment]
@WeinaJi  Thanks for informing about these changes! We will update bluecellulab accordingly.

**Comment by ilkilic** [comment]
I can confirm that https://github.com/BlueBrain/libsonata/pull/359 https://github.com/BlueBrain/libsonata/pull/358 do not affect bluecellulab

**Pull request merged**
