### PR TITLE
added high resolution logo

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by matz-e** [comment]
Shouldn't SONATA be all caps or all lowercase?

**Comment by jdcourcol** [comment]
> Shouldn't SONATA be all caps or all lowercase?

indeed. it should be all lowercase here.

**Comment by mgeplf** [comment]
ok, all lower case it will be, once I get the new version

**Comment by matz-e** [comment]
Also, can we get this in a vector format?

**Comment by mgeplf** [comment]
all lowercase:
https://github.com/BlueBrain/libsonata/blob/3c8e8e58b602fdf06190cddea9d6678dc5af98c0/README.md

**Comment by jdcourcol** [comment]
I think there should be 5 staves on the "music sheet" not 6. Or may be it is because there are 6 layers :) ?

**Comment by mgeplf** [comment]
I'm dying here.  Artistic liberty, I think.

**Comment by matz-e** [comment]
The top one could already be just a spike line…

**Comment by jdcourcol** [comment]
> The top one could already be just a spike line…

this is a good suggestion as the current logo does not convey the simulation part. I will talk to Michael.

**Comment by mgeplf** [comment]
I asked for that initially, but apparently it didn't work well.

**Comment by jdcourcol** [comment]
Ok, I asked Michael for an updated logo with a staff removed and eventually some spikes

**Comment by mgeplf** [comment]
ping

**Comment by matz-e** [comment]
svg?

**Pull request merged**
