### PR TITLE
v0.1.7 Changelog

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
Updates in Spack coming, too?

**Comment by mgeplf** [comment]
That's a separate issue, I just want to get this released.

**Review by matz-e — APPROVED** [review]

**Review by tomdele — APPROVED** [review]

**Comment by jdcourcol** [comment]
what are we waiting for to merge this one ?

**Comment by mgeplf** [comment]
https://github.com/BlueBrain/libsonata/pull/126

A couple more people testing the wheels, and I'm happy.

**Pull request merged**
