### PR TITLE
SONATA sim config: change the default file name for report

### PR DESCRIPTION
**Pull request by WeinaJi**

### CODE REVIEW

**Review by jorblancoa — APPROVED** [review]

**Review by mgeplf — APPROVED** [review]
Thanks!
LGTM; let's wait until https://github.com/BlueBrain/sonata-extension/pull/21/ is merged before merging this, though.

**Review by anilbey — APPROVED** [review]
Looks good to me, thanks

**Comment by WeinaJi** [comment]
Thank all for the reviews. I've merged https://github.com/BlueBrain/sonata-extension/pull/21. Could you please merge this PR @mgeplf ?

**Comment by mgeplf** [comment]
> Thank all for the reviews. I've merged [BlueBrain/sonata-extension#21](https://github.com/BlueBrain/sonata-extension/pull/21). Could you please merge this PR @mgeplf ?

Yup, done.  Thanks again.

**Pull request merged**
