### PR TITLE
Updating copyright year 2022

### PR DESCRIPTION
**Pull request by bbpgithubaudit**

### CODE REVIEW

**Review by mgeplf — APPROVED** [review]

**Comment by pramodk** [comment]
@mgeplf : how you are planning to address/fix other copyright year mentioned in the rest of the source: https://github.com/BlueBrain/libsonata/blob/da8291ac4694e2e74cba68adb67bda5e652b65c3/src/hdf5_mutex.cpp#L2

I am seeing the same situation about PR's created via @bbpgithubaudit and hence asking.

**Comment by mgeplf** [comment]
> @mgeplf : how you are planning to address/fix other copyright year mentioned in the rest of the source:
> I am seeing the same situation about PR's created via @bbpgithubaudit and hence asking.

Good question; in other OSS projects, ppl seem to update the copyright date when the file is updated, so maybe that's a way to do it?

**Comment by matz-e** [comment]
Spack does bulk updates to the copyright, just one commit / year.

**Comment by pramodk** [comment]
> ppl seem to update the copyright date when the file is updated, so maybe that's a way to do it?

This is resulting in a bit of inconsistency I think.  Something like Matthias mentioned might be better? 

By the way, copyright years mentioned in the source repos are also different/inconsistent. Maybe @bbpgithubaudit can help to `align` that and such updates could be done in a more robust + automated way.

**Comment by mgeplf** [comment]
> This is resulting in a bit of inconsistency I think.

Yeah, just noting that how other places do it.

> Maybe @bbpgithubaudit can help to align that and such updates could be done in a more robust + automated way.

Yup, that would be good.  Not sure if @alex4200 gets notified w/ @bbpgithubaudit , but I'm looping him in now.

**Comment by mgeplf** [comment]
I've mentioned the `SPDX` thing before, and that way the headers are small, and the date isn't required:
ex: https://github.com/torvalds/linux/blob/master/arch/arc/boot/dts/Makefile

**Pull request merged**
