### PR TITLE
Have the shim module document functionality

### LINKED ISSUE #160: Funny documentation
Running `pydoc3 libsonata` I see this, which is not very helpful:
```
Help on package libsonata:

NAME
    libsonata

DESCRIPTION
    # Needed so that mac wheels properly delocate:
    #  https://github.com/matthew-brett/delocate/issues/22

PACKAGE CONTENTS
    _libsonata

DATA
    version = '0.1.8'
```

### PR DESCRIPTION
**Pull request by matz-e**
Re-export all included classes via `__all__`, this fixes #160.

### CODE REVIEW

**Comment by mgeplf** [comment]
What does the output of `pydoc3 libsonata` give now?

**Comment by matz-e** [comment]
```
Help on package libsonata:

NAME
    libsonata - Python reader for SONATA circuit files

PACKAGE CONTENTS
    _libsonata

CLASSES
    builtins.Exception(builtins.BaseException)
        libsonata._libsonata.SonataError
    pybind11_builtins.pybind11_object(builtins.object)
        libsonata._libsonata.CircuitConfig
        libsonata._libsonata.EdgePopulation
        libsonata._libsonata.EdgeStorage
        libsonata._libsonata.ElementDataFrame
        libsonata._libsonata.ElementReportPopulation
        libsonata._libsonata.ElementReportReader
        libsonata._libsonata.NodePopulation
        libsonata._libsonata.NodeSets
        libsonata._libsonata.NodeStorage
        libsonata._libsonata.Selection
        libsonata._libsonata.SomaDataFrame
        libsonata._libsonata.SomaReportPopulation
        libsonata._libsonata.SomaReportReader
        libsonata._libsonata.SpikePopulation
        libsonata._libsonata.SpikeReader

    class CircuitConfig(pybind11_builtins.pybind11_object)
     |  Method resolution order:
     |      CircuitConfig
     |      pybind11_builtins.pybind11_object
     |      builtins.object
     |
     |  Methods defined here:
```
and so forth..

**Comment by matz-e** [comment]
I think a short usage header may actually be good, too… giving some examples how to use it.

**Comment by matz-e** [comment]
> I think a short usage header may actually be good, too… giving some examples how to use it.

On second thought… maybe let's leave it as it is for now.

**Review by mgeplf — APPROVED** [review]

**Comment by mgeplf** [comment]
tnx

**Pull request merged**
