### PR TITLE
selection: add a constructor from a vector of values

### PR DESCRIPTION
**Pull request by alkino**

### CODE REVIEW

**Comment by alkino** [comment]
Before I make this patch working, what about the idea?

Against?

I don't like this useless "fromValues" method, it adds nothing except indirection.

**Comment by mgeplf** [comment]
> Against?

Nope, looks fine to me.  Such is life that we have to keep backwards compat for now w/ the `Selection::fromValues`.  We just need to make sure there is symmetry with the other Selection creation, where an array of ints gives the 'flat' ids, and an array of tuples is interpreted as Ranges.

**Comment by tomdele** [comment]
It looks good indeed.

**Comment by alkino** [comment]
I think it's too hard to change this.

**Pull request closed without merging**
