### PR TITLE
bump HighFive to v2.7.1

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by mgeplf** [comment]
Apparently James needs a new release of libsonata so that the metadata field is available.  I'd prefer if HighFive was using a tagged version; the tests pass; but I'm not knowledgealbe about the internals enough to know if this is safe.

Can someone look?

**Review by WeinaJi — APPROVED** [review]
Looks good on the neurodamus side. I've built neurodamus with this branch and the simulation works as usual.

**Comment by WeinaJi** [comment]
Tag @alkino for review

**Review by alkino — APPROVED** [review]

**Comment by mgeplf** [comment]
Great, thanks everyone.

**Pull request merged**
