### PR TITLE
add check-clang-format github action

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by mgeplf** [comment]
@ferdonline, @tristan0x, @matz-e, @tomdele thoughts?

**Comment by matz-e** [comment]
> @ferdonline, @tristan0x, @matz-e, @tomdele thoughts?
> 
> BTW, this is to support #52

Clang version 9? :upside_down_face:

**Comment by mgeplf** [comment]
ie: you want clang v9?

**Comment by matz-e** [comment]
yes

**Comment by mgeplf** [comment]
I picked that b/c it's what's available on the cluster.

@ferdonline which version did you use when you did the #52 patch?

**Comment by tristan0x** [comment]
> I picked that b/c it's what's available on the cluster.
> 
> @ferdonline which version did you use when you did the #52 patch?

Good morning, LLVM 9 will be soon available on BB5 once @matz-e is done syncing our spack fork with the upstream repository. This will be the supported version along with GCC 8.3 to have full support  to C++17.

**Pull request merged**
