### PR TITLE
Add license files

### PR DESCRIPTION
**Pull request by arsenius7**
Do we also need AUTHORS / CONTRIBUTORS / ACKNOWLEDGMENTS.txt ?

### CODE REVIEW

**Comment by mgeplf** [comment]
Looks fine to me, but I don't know if we need the other files.

**Comment by arsenius7** [comment]
@jdcourcol , are there any other licensing formalities we should meet here?

**Comment by arsenius7** [comment]
@alex4200 , I have been told that you can see if the open-sourced code meets our standards (with regard to licensing etc).
Can you please take a look and let me know what is missing? Thanks.

**Comment by alex4200** [comment]
@arsenius7 According to the checklist [here](https://bbpteam.epfl.ch/project/spaces/display/BBPSTD/Open+Source#OpenSource-Checklist) still many items are missing. Please have a look and let me know things unclear.

**Comment by arsenius7** [comment]
Of the "many items missing" (related to licensing), I see  licensing header included to every source file. Does it mean I should just copy LICENSE.txt content to every file? Also, as mentioned above, not sure whether ACKNOWLEDGEMENTS here are need, and what should go there.

**Comment by alex4200** [comment]
These are good questions we need to clarify. We never used that checklist before, so we still need to iron out the details. 

I will add you to a meeting tomorrow.

**Comment by arsenius7** [comment]
Added boilerplate license header to *.cpp / *.hpp files.
@alex4200 , I figure ACKNOWLEDGEMENTS and CONTRIBUTING are optional?

**Comment by alex4200** [comment]
Yes, the boilerplate goes only into source files/

**Pull request merged**
